[package]
name = "gdble"
version = "0.3.0"
edition = "2021"

[dependencies]
godot = "0.4.5"
btleplug = "0.11.8"
tokio = { version = "1.40", features = ["full"] }
futures = "0.3"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = true

